### ISSUE TITLE
Submission to Melpa

### ISSUE THREAD

**Issue by ag91** [riscy/doctest#4]
Hello!
Thanks for the great package!
I have kept [a fork of it](https://github.com/ag91/doctest) and I was asked to submit the package to Melpa.
I could look into doing that, if this is something you are not planning on doing as it seems it could benefit others.
Please let me know if there is any problem with that, meanwhile I will slowly get the fork up to speed with Melpa requirements.
In case of silence I will try another ping before submitting (worst case scenario you can reject the submission on Melpa ;) )

Thanks again for doctest.el :)

**Comment by riscy** [comment]
Yes, absolutely - I am happy to hand over maintainership to you, @ag91. :)

**Comment by ag91** [comment]
okay cool, I will submit it to Melpa then. Do you want to give me maintainership of your repo or you want just to add a note to the README to say that (not so :)) active dev moved to the fork?

**Comment by suhail-singh** [comment]
FWIW, one way to transfer maintainership that prevents repo fragmentation would be for, say, an `emacs-doctest` github organization to be created by @ag91 . @riscy could then be added as a collaborator and he could transfer the repo over to the organization. Then `emacs-doctest/doctest` (for which @ag91 would have write permissions as well) could be the repo that's submitted to MELPA.

**Comment by ag91** [comment]
I will submit the fork to Melpa for now and improve on it later if necessary. Thanks!

**Comment by riscy** [comment]
@ag91 I'm happy to transfer ownership of this over to you (relocate the repo, create an org, do nothing, or whichever you prefer!)

**Comment by ag91** [comment]
I think is enough to redirect users to my fork with a note in the README, if you have time for that.

**Comment by riscy** [comment]
Redirect added.

I also discovered I had two unpushed [commits](https://github.com/riscy/doctest/commits/master/) from three years ago (!) that may or may not be relevant to you, and pushed those up as well: bec902c297168635a8b3f30d7e675b297d3a7280, 40ee372b4abb925ad54dc2ae8958b4c0e6a7467d
